from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import threading
import time
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("archify_plan_under_test", ROOT / "scripts" / "archify_plan.py")
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def model_for(count: int = 2, edges: list[dict[str, str]] | None = None) -> dict[str, object]:
    tasks = [{"number": str(index + 1), "title": f"Task {index + 1}"} for index in range(count)]
    return {
        "schemaVersion": 2,
        "parserVersion": "2.0.0",
        "tasks": tasks,
        "edges": edges if edges is not None else ([{"from": "1", "to": "2"}] if count > 1 else []),
    }


def fake_svg() -> bytes:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 420 180">'
        '<defs><marker id="arrow"><path d="M0 0 L4 2 L0 4 Z"/></marker></defs>'
        '<style>.node { fill: #eee; stroke: #222; }</style>'
        '<rect class="node" x="20" y="20" width="80" height="40"/>'
        '<path d="M100 40 H300" marker-end="url(#arrow)"/></svg>'
    ).encode("utf-8")


def metadata_svg() -> bytes:
    return (
        '<svg viewBox="0 0 120 80" role="img" lang="en" '
        'aria-labelledby="archify-diagram-title archify-diagram-description" '
        'xmlns="http://www.w3.org/2000/svg">'
        '<style>.node { fill: #eee; }</style>'
        '<title id="archify-diagram-title" data-origin="official">旧title</title>'
        '<desc id="archify-diagram-description" data-origin="official">A workflow diagram generated by Archify.</desc>'
        '<g><title>node title</title><rect class="node" x="10" y="10" width="40" height="20"/></g>'
        '</svg>'
    ).encode("utf-8")


def fake_descriptor() -> dict[str, object]:
    return {
        "schemaVersion": 1,
        "backend": MODULE.EXPECTED_CONTAINER_BACKEND,
        "policyId": MODULE.EXPECTED_CONTAINER_POLICY,
        "image": "sha256:" + "1" * 64,
        "baseImage": MODULE.EXPECTED_BASE_IMAGE,
        "sourceManifestSha256": MODULE.EXPECTED_MANIFEST_SHA256,
        "sourceConfigSha256": MODULE.EXPECTED_CONFIG_SHA256,
        "bridgeSha256": "2" * 64,
        "entrypointSha256": "3" * 64,
        "seccompSha256": MODULE.EXPECTED_SECCOMP_SHA256,
        "dockerExecutable": MODULE.EXPECTED_DOCKER_EXECUTABLE,
        "dockerRealpath": MODULE.EXPECTED_DOCKER_REALPATH,
        "dockerSha256": MODULE.EXPECTED_DOCKER_SHA256,
        "nodeExecutable": MODULE.EXPECTED_NODE_EXECUTABLE,
        "nodeSha256": MODULE.EXPECTED_NODE_SHA256,
        "nodeVersion": MODULE.EXPECTED_NODE_VERSION,
        "chromeExecutable": MODULE.EXPECTED_CHROME_EXECUTABLE,
        "chromeSha256": MODULE.EXPECTED_CHROME_SHA256,
        "chromeVersion": MODULE.EXPECTED_CHROME_VERSION,
    }


def fake_receipt(raw: bytes, revision: str = "revision-test") -> dict[str, object]:
    digest = MODULE._sha256_bytes(raw)
    empty_digest = "0" * 64
    return {
        "schemaVersion": 1,
        "ok": True,
        "status": "verified",
        "command": "archify-render",
        "diagramType": "workflow",
        "revision": revision,
        "source": {"revision": revision, "fileCount": 190, "manifestSha256": MODULE.EXPECTED_MANIFEST_SHA256},
        "renderer": {
            "command": "deliver",
            "quality": "standard",
            "artifact": {"sha256": empty_digest, "bytes": 1},
        },
        "html": {
            "rawSha256": empty_digest,
            "rawBytes": 1,
            "sanitizedSha256": empty_digest,
            "sanitizedBytes": 1,
        },
        "browser": {
            "theme": "light",
            "sandboxPolicy": MODULE.EXPECTED_CONTAINER_POLICY,
            "sandboxProfileSha256": MODULE.EXPECTED_SECCOMP_SHA256,
            "chromeExecutable": MODULE.EXPECTED_CHROME_EXECUTABLE,
            "chromiumSandbox": True,
            "pipe": True,
            "freshContext": True,
            "sha256": digest,
            "bytes": len(raw),
            "playwright": {
                "version": MODULE.EXPECTED_PLAYWRIGHT_VERSION,
                "packageSha256": MODULE.EXPECTED_PLAYWRIGHT_PACKAGE_SHA256,
                "coreSha256": MODULE.EXPECTED_PLAYWRIGHT_CORE_SHA256,
                "lockSha256": MODULE.EXPECTED_PLAYWRIGHT_LOCK_SHA256,
            },
        },
        "rawSvg": {"path": "raw.svg", "sha256": digest, "bytes": len(raw)},
        "runtime": {
            "backend": MODULE.EXPECTED_CONTAINER_BACKEND,
            "image": "sha256:" + "1" * 64,
            "baseImage": MODULE.EXPECTED_BASE_IMAGE,
            "bridgeSha256": "2" * 64,
            "entrypointSha256": "3" * 64,
            "nodeSha256": MODULE.EXPECTED_NODE_SHA256,
            "nodeVersion": MODULE.EXPECTED_NODE_VERSION,
            "chromeSha256": MODULE.EXPECTED_CHROME_SHA256,
            "chromeVersion": MODULE.EXPECTED_CHROME_VERSION,
        },
    }


def fake_container_inspect() -> dict[str, object]:
    descriptor = fake_descriptor()
    seccomp = MODULE.SECCOMP_PATH.read_text(encoding="utf-8")
    env = [
        "HOME=/tmp/browser", "TMPDIR=/tmp/browser", "PLAYWRIGHT_BROWSERS_PATH=/ms-playwright",
        "LANG=C", "LC_ALL=C", "TZ=UTC",
        f"{MODULE.SANDBOX_MARKER}={MODULE.EXPECTED_CONTAINER_POLICY}",
        f"{MODULE.SANDBOX_PROFILE_HASH_MARKER}={descriptor['seccompSha256']}",
        f"ARCHIFY_CONTAINER_IMAGE={descriptor['image']}",
    ]
    return {
        "Name": "/archify-plan-test",
        "Id": "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        "AppArmorProfile": "docker-default",
        "Config": {
            "Image": descriptor["image"], "User": "1000:1000", "WorkingDir": "/tmp/run",
            "OpenStdin": True, "Tty": False, "Entrypoint": [MODULE.EXPECTED_NODE_EXECUTABLE],
            "Cmd": ["/app/scripts/archify_container.mjs"], "Env": env,
        },
        "HostConfig": {
            "NetworkMode": "none", "IpcMode": "private", "PidMode": "", "ReadonlyRootfs": True,
            "Privileged": False, "CapAdd": None, "CapDrop": ["ALL"], "Binds": None,
            "Devices": None, "DeviceRequests": None, "Memory": 1024 * 1024 * 1024,
            "MemorySwap": 1024 * 1024 * 1024, "NanoCpus": 1_000_000_000, "PidsLimit": 128,
            "ShmSize": 64 * 1024 * 1024,
            "SecurityOpt": ["no-new-privileges=true", "apparmor=docker-default", f"seccomp={seccomp}"],
            "Ulimits": [
                {"Name": "cpu", "Soft": 60, "Hard": 61},
                {"Name": "fsize", "Soft": MODULE.CONTAINER_FSIZE_LIMIT, "Hard": MODULE.CONTAINER_FSIZE_LIMIT},
                {"Name": "nofile", "Soft": 512, "Hard": 512}, {"Name": "core", "Soft": 0, "Hard": 0},
            ],
            "Tmpfs": {
                "/tmp/run": "rw,noexec,nosuid,nodev,size=32m,nr_inodes=128,uid=1000,gid=1000,mode=0700",
                "/tmp/browser": "rw,noexec,nosuid,nodev,size=64m,nr_inodes=4096,uid=1000,gid=1000,mode=0700",
            },
        },
        "Mounts": [], "State": {"Running": False},
    }


class ArchifyPlanTests(unittest.TestCase):
    def invoke_with_fake(self, fake, callback):
        with TemporaryDirectory(prefix="archify-plan-test-") as directory:
            with mock.patch.object(MODULE, "CACHE_ROOT", Path(directory) / "cache"), mock.patch.object(
                MODULE, "_load_config", return_value=("revision-test", fake_descriptor())
            ), mock.patch.object(MODULE, "_invoke_renderer", side_effect=fake):
                return callback()

    def test_projection_contains_only_task_titles_and_explicit_edges(self) -> None:
        model = model_for()
        projection = MODULE.project_plan("raw", model)

        self.assertEqual(set(projection["overviewModel"]), {"tasks", "edges"})
        self.assertEqual(set(projection["overviewModel"]["tasks"][0]), {"number", "title"})
        self.assertEqual(projection["overviewModel"]["edges"], [{"from": "1", "to": "2"}])
        self.assertNotIn("status", json.dumps(projection["overviewModel"], ensure_ascii=False))
        self.assertEqual(projection["planSha256"], MODULE._sha256_bytes(b"raw"))

    def test_progress_only_model_change_keeps_cached_svg_and_model_hash(self) -> None:
        calls: list[int] = []

        def fake(spec_path, run_dir, node_path, **_kwargs):
            calls.append(1)
            raw = fake_svg()
            (run_dir / "raw.svg").write_bytes(raw)
            spec = json.loads(spec_path.read_text(encoding="utf-8"))
            receipt = fake_receipt(raw)
            receipt["nodeCount"] = len(spec["nodes"])
            receipt["edgeCount"] = len(spec["edges"])
            return receipt, raw

        def run():
            first = MODULE.archify_for_plan("same plan", {**model_for(), "progress": {"done": 0}})
            second = MODULE.archify_for_plan("same plan", {**model_for(), "progress": {"done": 2}})
            self.assertEqual(first["status"], "verified")
            self.assertEqual(second["status"], "verified")
            self.assertEqual(first["overview"]["svgSha256"], second["overview"]["svgSha256"])
            self.assertEqual(first["source"]["overviewModelSha256"], second["source"]["overviewModelSha256"])
            self.assertEqual(calls, [1])
            return first

        payload = self.invoke_with_fake(fake, run)
        self.assertEqual(payload["source"]["taskIds"], ["1", "2"])

    def test_plan_bytes_are_hashed_without_normalization(self) -> None:
        model = model_for(1)
        first = MODULE.project_plan("title\n", model)
        second = MODULE.project_plan("title\r\n", model)

        self.assertNotEqual(first["planSha256"], second["planSha256"])
        self.assertEqual(first["overviewModelSha256"], second["overviewModelSha256"])

    def test_layout_preserves_chain_independent_and_diamond_cardinality(self) -> None:
        chain_edges = [{"from": str(index), "to": str(index + 1)} for index in range(1, 20)]
        chain = MODULE._workflow_spec(MODULE.project_plan("chain", model_for(20, chain_edges)))
        self.assertEqual(len(chain["nodes"]), 20)
        self.assertEqual(len(chain["edges"]), 19)
        self.assertEqual(len(chain["lanes"]), 4)
        self.assertEqual([node["col"] for node in chain["nodes"][:6]], list(range(6)))

        independent = MODULE._workflow_spec(MODULE.project_plan("independent", model_for(20, [])))
        self.assertEqual(len(independent["lanes"]), 1)
        self.assertEqual(len(independent["edges"]), 0)
        self.assertEqual([node.get("yOffset") for node in independent["nodes"][:20:6]], [-96.0, -32.0, 32.0, 96.0])

        numbers = [str(index + 1) for index in range(20)]
        diamond_edges = [{"from": "1", "to": str(index)} for index in range(2, 8)]
        diamond_edges += [{"from": str(index), "to": str(index + 6)} for index in range(2, 8)]
        diamond_edges += [{"from": str(index), "to": str(index + 6)} for index in range(8, 14)]
        diamond_edges += [{"from": str(index), "to": "20"} for index in range(14, 20)]
        diamond_model = {"tasks": [{"number": number, "title": number} for number in numbers], "edges": diamond_edges}
        diamond = MODULE._workflow_spec(MODULE.project_plan("diamond", diamond_model))
        self.assertEqual(len(diamond["nodes"]), 20)
        self.assertEqual(len(diamond["edges"]), 24)
        self.assertEqual({node["type"] for node in diamond["nodes"]}, {"external"})

    def test_cycle_unknown_and_duplicate_edges_are_invalid(self) -> None:
        cases = [
            ({"tasks": model_for(2)["tasks"], "edges": [{"from": "1", "to": "2"}, {"from": "2", "to": "1"}]}, "cycle"),
            ({"tasks": model_for(1)["tasks"], "edges": [{"from": "1", "to": "9"}]}, "unknown"),
            ({"tasks": model_for(2)["tasks"], "edges": [{"from": "1", "to": "2"}, {"from": "1", "to": "2"}]}, "duplicate"),
        ]
        for model, _label in cases:
            payload = MODULE.archify_for_plan("invalid", model)
            self.assertEqual(payload["status"], "invalid")
            self.assertNotIn("overview", payload)

    def test_parser_failure_uses_safe_japanese_message(self) -> None:
        with mock.patch.object(MODULE, "_load_plan_contract_module", side_effect=RuntimeError("unknown dependency: Task 99")):
            payload = MODULE.archify_for_plan("untrusted plan")
        self.assertEqual(payload["status"], "invalid")
        self.assertEqual(payload["message"], "計画の構造を確認できません。")
        self.assertNotIn("Task 99", payload["message"])

    def test_bounds_reject_oversized_raw_task_and_title(self) -> None:
        oversized_raw = MODULE.archify_for_plan("x" * (MODULE.RAW_PLAN_LIMIT + 1), model_for(1))
        oversized_tasks = MODULE.archify_for_plan("tasks", model_for(MODULE.TASK_LIMIT + 1, []))
        oversized_title_model = {"tasks": [{"number": "1", "title": "x" * (MODULE.TITLE_LIMIT + 1)}], "edges": []}
        oversized_title = MODULE.archify_for_plan("title", oversized_title_model)

        self.assertEqual(oversized_raw["status"], "invalid")
        self.assertEqual(oversized_tasks["status"], "invalid")
        self.assertEqual(oversized_title["status"], "invalid")

    def test_svg_injection_is_error_and_never_published(self) -> None:
        def fake(spec_path, run_dir, node_path, **_kwargs):
            raw = b'<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>'
            (run_dir / "raw.svg").write_bytes(raw)
            return {"ok": True}, raw

        payload = self.invoke_with_fake(
            fake,
            lambda: MODULE.archify_for_plan("unsafe", model_for()),
        )
        self.assertEqual(payload["status"], "error")
        self.assertNotIn("overview", payload)

    def test_svg_namespace_depth_css_and_external_fragments_are_rejected(self) -> None:
        cases = [
            b"<svg></svg>",
            b'<svg xmlns="http://www.w3.org/2000/svg"><style>@import "x.css";</style></svg>',
            b'<svg xmlns="http://www.w3.org/2000/svg"><style>@im\\70ort "x.css";</style></svg>',
            b'<svg xmlns="http://www.w3.org/2000/svg"><rect fill="url(remote.svg#paint)"/></svg>',
            b'<svg xmlns="http://www.w3.org/2000/svg" xmlns:x="urn:foreign"><x:g/></svg>',
            b'<svg xmlns="http://www.w3.org/2000/svg"><rect begin="0s"/></svg>',
            b'<svg xmlns="http://www.w3.org/2000/svg">' + b"<g>" * (MODULE.SVG_DEPTH_LIMIT + 1) + b"</g>" * (MODULE.SVG_DEPTH_LIMIT + 1) + b"</svg>",
        ]
        for raw in cases:
            with self.assertRaises(MODULE._RendererFailure):
                MODULE._validate_svg(raw)
        MODULE._validate_svg(b'<svg xmlns="http://www.w3.org/2000/svg"><rect fill="url(#paint)"/></svg>')

    def test_svg_metadata_normalizes_root_text_and_preserves_ids_attributes_and_geometry(self) -> None:
        raw = metadata_svg()
        _raw_text, raw_digest = MODULE._validate_svg(raw)
        final, final_digest = MODULE.sanitize_svg(
            raw, {"meta": {"title": "日本語 <計画> & title"}}
        )
        root = ET.fromstring(final)
        direct = {MODULE._local_name(child.tag): child for child in list(root) if isinstance(child.tag, str)}
        title = direct["title"]
        desc = direct["desc"]
        self.assertEqual(title.text, "日本語 <計画> & title")
        self.assertEqual(desc.text, "Taskと明示された依存関係を示す計画overview")
        self.assertEqual(title.get("id"), "archify-diagram-title")
        self.assertEqual(desc.get("id"), "archify-diagram-description")
        self.assertEqual(title.get("data-origin"), "official")
        self.assertEqual(desc.get("data-origin"), "official")
        self.assertEqual(root.get("aria-labelledby"), "archify-diagram-title archify-diagram-description")
        self.assertEqual(final_digest, raw_digest)
        self.assertEqual(MODULE._svg_geometry_digest(root), raw_digest)
        self.assertIn(
            ".node { fill: #eee; }",
            "".join(next(child.itertext()) for child in list(root) if MODULE._local_name(child.tag) == "style"),
        )
        self.assertEqual(
            next(child for child in root.iter() if MODULE._local_name(child.tag) == "title" and child is not title).text,
            "node title",
        )

    def test_svg_metadata_adds_missing_desc_and_rejects_duplicate_root_metadata(self) -> None:
        raw = (
            b'<svg xmlns="http://www.w3.org/2000/svg"><title id="title-id">old</title>'
            b'<rect x="1" y="1" width="2" height="2"/></svg>'
        )
        final, _digest = MODULE.sanitize_svg(raw, {"meta": {"title": "new"}})
        root = ET.fromstring(final)
        direct = [child for child in list(root) if isinstance(child.tag, str)]
        self.assertEqual([MODULE._local_name(child.tag) for child in direct].count("desc"), 1)
        self.assertEqual(next(child for child in direct if MODULE._local_name(child.tag) == "desc").text, "Taskと明示された依存関係を示す計画overview")
        duplicate = b'<svg xmlns="http://www.w3.org/2000/svg"><title>one</title><title>two</title></svg>'
        with self.assertRaisesRegex(MODULE._RendererFailure, "metadataが重複"):
            MODULE.sanitize_svg(duplicate, {"meta": {"title": "new"}})

    def test_bridge_receipt_requires_sandbox_and_official_export_evidence(self) -> None:
        receipt = fake_receipt(fake_svg())
        del receipt["browser"]["sandboxProfileSha256"]
        with self.assertRaises(MODULE._RendererFailure):
            MODULE._validate_bridge_receipt(receipt, revision="revision-test", profile_hash=None)

    def test_tampered_cache_is_a_miss_and_old_svg_is_not_returned(self) -> None:
        calls: list[int] = []

        def fake(spec_path, run_dir, node_path, **_kwargs):
            calls.append(1)
            raw = fake_svg()
            (run_dir / "raw.svg").write_bytes(raw)
            spec = json.loads(spec_path.read_text(encoding="utf-8"))
            receipt = fake_receipt(raw)
            receipt["nodeCount"] = len(spec["nodes"])
            receipt["edgeCount"] = len(spec["edges"])
            return receipt, raw

        def run():
            first = MODULE.archify_for_plan("tamper", model_for())
            directory, _bundle, svg_path = MODULE._cache_paths("revision-test", first["source"]["planSha256"])
            svg_path.write_text("<svg/>", encoding="utf-8")
            with mock.patch.object(MODULE, "_invoke_renderer", side_effect=MODULE._RendererFailure("renderer unavailable")):
                second = MODULE.archify_for_plan("tamper", model_for())
            self.assertEqual(first["status"], "verified")
            self.assertEqual(second["status"], "error")
            self.assertNotIn("overview", second)
            self.assertEqual(calls, [1])

        self.invoke_with_fake(fake, run)

    def test_parallel_same_plan_serializes_generation_and_shares_cache(self) -> None:
        calls: list[int] = []
        calls_lock = threading.Lock()

        def fake(spec_path, run_dir, node_path, **_kwargs):
            with calls_lock:
                calls.append(1)
            time.sleep(0.05)
            raw = fake_svg()
            (run_dir / "raw.svg").write_bytes(raw)
            spec = json.loads(spec_path.read_text(encoding="utf-8"))
            receipt = fake_receipt(raw)
            receipt["nodeCount"] = len(spec["nodes"])
            receipt["edgeCount"] = len(spec["edges"])
            return receipt, raw

        def run():
            results: list[dict[str, object]] = []
            result_lock = threading.Lock()

            def generate():
                result = MODULE.archify_for_plan("parallel", model_for())
                with result_lock:
                    results.append(result)

            threads = [threading.Thread(target=generate) for _ in range(2)]
            for thread in threads:
                thread.start()
            for thread in threads:
                thread.join()
            self.assertEqual([item["status"] for item in results], ["verified", "verified"])
            self.assertEqual(len(calls), 1)

        self.invoke_with_fake(fake, run)

    def test_container_envelope_requires_canonical_base64_and_hash(self) -> None:
        raw = fake_svg()
        envelope = {
            "schemaVersion": 1,
            "protocol": MODULE.EXPECTED_CONTAINER_PROTOCOL,
            "ok": True,
            "receipt": fake_receipt(raw),
            "rawSvg": {
                "encoding": "base64",
                "bytes": len(raw),
                "sha256": MODULE._sha256_bytes(raw),
                "data": __import__("base64").b64encode(raw).decode("ascii"),
            },
        }
        receipt, decoded = MODULE._decode_container_envelope(
            json.dumps(envelope, separators=(",", ":")).encode("utf-8"), fake_descriptor()
        )
        self.assertEqual(receipt["runtime"]["image"], fake_descriptor()["image"])
        self.assertEqual(decoded, raw)
        envelope["rawSvg"]["data"] = envelope["rawSvg"]["data"][:-2] + "AA"
        with self.assertRaises(MODULE._RendererFailure):
            MODULE._decode_container_envelope(
                json.dumps(envelope, separators=(",", ":")).encode("utf-8"), fake_descriptor()
            )

    def test_container_create_is_fixed_and_has_no_host_mount_or_extra_env(self) -> None:
        descriptor = fake_descriptor()
        command = MODULE._container_create_command(descriptor, "archify-plan-test", "archify-plan-test")
        self.assertEqual(command[:3], [MODULE.EXPECTED_DOCKER_EXECUTABLE, "--context", MODULE.EXPECTED_DOCKER_CONTEXT])
        self.assertIn("--pull", command)
        self.assertEqual(command[command.index("--pull") + 1], "never")
        self.assertIn("--read-only", command)
        self.assertIn("--cap-drop", command)
        self.assertEqual(command[command.index("--cap-drop") + 1], "ALL")
        self.assertIn(
            f"fsize={MODULE.CONTAINER_FSIZE_LIMIT}:{MODULE.CONTAINER_FSIZE_LIMIT}", command
        )
        self.assertNotIn("--mount", command)
        self.assertNotIn("-v", command)
        self.assertNotIn("--volume", command)
        env_values = [command[index + 1] for index, value in enumerate(command[:-1]) if value == "--env"]
        self.assertEqual(
            set(env_values),
            {
                "HOME=/tmp/browser", "TMPDIR=/tmp/browser", "LANG=C", "LC_ALL=C", "TZ=UTC",
                "PLAYWRIGHT_BROWSERS_PATH=/ms-playwright",
                f"{MODULE.SANDBOX_MARKER}={MODULE.EXPECTED_CONTAINER_POLICY}",
                f"{MODULE.SANDBOX_PROFILE_HASH_MARKER}={MODULE.EXPECTED_SECCOMP_SHA256}",
                f"ARCHIFY_CONTAINER_IMAGE={descriptor['image']}",
            },
        )

    def test_container_inspect_requires_exact_tmpfs_and_outer_device_boundaries(self) -> None:
        descriptor = fake_descriptor()
        self.assertEqual(
            MODULE._verify_container_inspect(fake_container_inspect(), descriptor, "archify-plan-test"),
            "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        )
        for replacement in (
            ("/tmp/run", "rw,noexec,nosuid,nodev,size=32m,nr_inodes=1280,uid=1000,gid=1000,mode=0700"),
            ("/tmp/run", "rw,noexec,nosuid,nodev,size=32mb,nr_inodes=128,uid=1000,gid=1000,mode=0700"),
            ("/tmp/run", "rw,noexec,nosuid,nodev,size=32m,nr_inodes=128,uid=10000,gid=1000,mode=0700"),
        ):
            info = fake_container_inspect()
            info["HostConfig"]["Tmpfs"][replacement[0]] = replacement[1]
            with self.assertRaises(MODULE._RendererBlocked):
                MODULE._verify_container_inspect(info, descriptor, "archify-plan-test")
        info = fake_container_inspect()
        info["HostConfig"]["Tmpfs"]["/tmp/extra"] = "rw,size=1m"
        with self.assertRaises(MODULE._RendererBlocked):
            MODULE._verify_container_inspect(info, descriptor, "archify-plan-test")
        info = fake_container_inspect()
        info["HostConfig"]["Devices"] = [{}]
        with self.assertRaises(MODULE._RendererBlocked):
            MODULE._verify_container_inspect(info, descriptor, "archify-plan-test")

    def test_cleanup_requires_successful_queries_and_limited_missing_rm(self) -> None:
        def missing_rm(args, *, deadline, input_bytes=b"", stdout_limit=0, check=True, **_kwargs):
            if args[0] == "rm":
                return 1, b"", f"Error response from daemon: No such container: {args[-1]}".encode()
            return 0, b"", b""

        with mock.patch.object(MODULE, "_docker_call", side_effect=missing_rm):
            MODULE._cleanup_container(
                "archify-plan-test", "abcdef012345", "archify-plan-test", deadline=time.monotonic() + 2
            )

        def failed_query(args, *, deadline, input_bytes=b"", stdout_limit=0, check=True, **_kwargs):
            if args[0] == "ps":
                return 1, b"", b"daemon unavailable"
            return 0, b"", b""

        with mock.patch.object(MODULE, "_docker_call", side_effect=failed_query):
            with self.assertRaisesRegex(MODULE._RendererFailure, "停止を確認できません"):
                MODULE._cleanup_container(
                    "archify-plan-test", "abcdef012345", "archify-plan-test", deadline=time.monotonic() + 2
                )

        def failed_rm(args, *, deadline, input_bytes=b"", stdout_limit=0, check=True, **_kwargs):
            if args[0] == "rm":
                return 1, b"", b"permission denied"
            return 0, b"", b""

        with mock.patch.object(MODULE, "_docker_call", side_effect=failed_rm):
            with self.assertRaisesRegex(MODULE._RendererFailure, "停止を確認できません"):
                MODULE._cleanup_container(
                    "archify-plan-test", "abcdef012345", "archify-plan-test", deadline=time.monotonic() + 2
                )

    def test_cleanup_rechecks_label_after_create_id_is_missing(self) -> None:
        label_queries = 0
        removed: list[str] = []
        delayed_id = "abcdef0123456789"

        def delayed_label(args, *, deadline, input_bytes=b"", stdout_limit=0, check=True, **_kwargs):
            nonlocal label_queries
            if args[0] == "rm":
                removed.append(args[-1])
                return 0, b"", b""
            if args[0] == "ps" and args[-1].startswith("label="):
                label_queries += 1
                return 0, ((b"" if label_queries == 1 or label_queries > 2 else delayed_id.encode()) + b"\n"), b""
            return 0, b"", b""

        with mock.patch.object(MODULE, "_docker_call", side_effect=delayed_label):
            MODULE._cleanup_container(
                "archify-plan-test", None, "archify-plan-test", deadline=time.monotonic() + 2
            )
        self.assertIn(delayed_id, removed)
        self.assertGreaterEqual(label_queries, 3)

    def test_container_cleanup_failure_is_reported_after_primary_failure(self) -> None:
        with TemporaryDirectory(prefix="archify-renderer-test-") as directory:
            root = Path(directory)
            run_dir = root / "run"
            run_dir.mkdir(mode=0o700)
            spec_path = run_dir / "spec.json"
            spec_path.write_bytes(b"{}")
            spec_path.chmod(0o600)
            with mock.patch.object(MODULE, "_verify_context", side_effect=MODULE._RendererFailure("primary")), mock.patch.object(
                MODULE, "_cleanup_container", side_effect=MODULE._RendererFailure("cleanup")
            ):
                with self.assertRaisesRegex(MODULE._RendererFailure, "停止を確認できません"):
                    MODULE._invoke_renderer(spec_path, run_dir, fake_descriptor(), timeout=6)

    def test_staging_cleanup_does_not_hide_unlink_failure(self) -> None:
        with TemporaryDirectory(prefix="archify-staging-test-") as directory:
            root = Path(directory) / "staging"
            root.mkdir(mode=0o700)
            staged = root / "spec.json"
            staged.write_bytes(b"{}")
            with mock.patch.object(Path, "unlink", side_effect=OSError("locked")):
                with self.assertRaisesRegex(MODULE._RendererFailure, "後片付けを確認できません"):
                    MODULE._cleanup_staging_directory(root)
            self.assertTrue(staged.exists())
            MODULE._cleanup_staging_directory(root)

    def test_bounded_process_rejects_stdout_overflow_without_waiting_forever(self) -> None:
        with self.assertRaisesRegex(MODULE._RendererFailure, "出力上限"):
            MODULE._bounded_process(
                [sys.executable, "-c", "import sys;sys.stdout.write('x'*700000)"],
                b"",
                cwd=ROOT,
                env={"PATH": "/usr/bin:/bin", "LANG": "C", "LC_ALL": "C", "TZ": "UTC"},
                timeout=2,
                stdout_limit=64 * 1024,
                stderr_limit=64 * 1024,
            )

    def test_cleanup_checks_label_and_both_id_paths(self) -> None:
        calls: list[list[str]] = []

        def fake_call(args, *, deadline, input_bytes=b"", stdout_limit=0, check=True, **_kwargs):
            calls.append(args)
            return 0, b"", b""

        with mock.patch.object(MODULE, "_docker_call", side_effect=fake_call):
            MODULE._cleanup_container(
                "archify-plan-test", "abcdef012345", "archify-plan-test", deadline=time.monotonic() + 2
            )
        self.assertIn(["rm", "--force", "archify-plan-test"], calls)
        self.assertIn(["rm", "--force", "abcdef012345"], calls)
        self.assertGreaterEqual(sum(args[:2] == ["ps", "-aq"] for args in calls), 3)

    def test_cache_rejects_runtime_image_tampering(self) -> None:
        def fake(spec_path, run_dir, _renderer_config, **_kwargs):
            raw = fake_svg()
            receipt = fake_receipt(raw)
            receipt["nodeCount"] = 2
            receipt["edgeCount"] = 1
            return receipt, raw

        def run():
            first = MODULE.archify_for_plan("runtime tamper", model_for())
            directory, bundle_path, _svg_path = MODULE._cache_paths("revision-test", first["source"]["planSha256"])
            bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
            bundle["_rendererReceipt"]["runtime"]["image"] = "sha256:" + "f" * 64
            bundle_path.write_text(json.dumps(bundle, ensure_ascii=False), encoding="utf-8")
            self.assertIsNone(MODULE._cache_hit(MODULE.project_plan("runtime tamper", model_for()), "revision-test", fake_descriptor()))
            self.assertTrue(directory.is_dir())

        self.invoke_with_fake(fake, run)

    def test_cli_accepts_only_content_and_returns_json_status(self) -> None:
        result = subprocess.run(
            ["python3", "scripts/archify_plan.py"],
            cwd=ROOT,
            input=json.dumps({"content": ""}),
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0)
        payload = json.loads(result.stdout)
        self.assertEqual(payload["provider"], "archify")
        self.assertEqual(payload["status"], "empty")
        self.assertEqual(result.stderr, "")

        duplicate = subprocess.run(
            ["python3", "scripts/archify_plan.py"],
            cwd=ROOT,
            input='{"content":"","content":""}',
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(json.loads(duplicate.stdout)["status"], "invalid")


if __name__ == "__main__":
    unittest.main()
